### ISSUE TITLE
DeprecationWarning: The truth value of an empty array is ambiguous.

### ISSUE THREAD

**Issue by gogotrace** [rajatsen91/CCIT#3]
Hey there, CCIT contributors,

I tryed the following commands.

```
data = DataGen.generate_samples_cos(dx=1,dy=1,dz=20,sType='NI')  #non-CI dataset, pvalue should be low

X = data[:,0:1]
Y = data[:,1:2]
Z = data[:,2::]

pvalue = CCIT.CCIT(X,Y,Z) 
```

And received the following warning.

C:\Users\XXX\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

The output pvalue is 0.014717305527501225, which looks fine. So is everything alright with my installation? Could you kindly let me know if there is anything I can do to with the warning?

Thank you,
gogotrace

**Comment by gogotrace** [comment]
Problem solved, see [this](https://stackoverflow.com/questions/48687375/deprecation-error-in-sklearn-about-empty-array-without-any-empty-array-in-my-cod).

**Comment by rajatsen91** [comment]
Sorry for the delay and yes you can ignore it. Thanks for the update.
