### ISSUE TITLE
Add versions to package requirements in setup.py

### ISSUE THREAD

**Issue by mashrurmorshed** [rajatsen91/CCIT#5]
I tried running CCIT on a clean virtualenv. While the installation works fine, there are numerous sklearn and XGBoost based errors which are mostly due to depreciation. Even the example in the README doesn't work.

Would it be possible to specify the exact versions of the requirements for CCIT? I believe that would solve most of the problems and make CCIT future-proof.

For example, in [setup.py](https://github.com/rajatsen91/CCIT/blob/master/setup.py) we have:

```python
install_requires=[
          'markdown',
          'xgboost',
          'pandas',
          'numpy',
          'scikit-learn',
          'scipy',
          'matplotlib'
      ],
```

So the correct/working package versions of these 7 packages is needed. In fact, I think only xgboost and sklearn's correct package number should solve it.

**Comment by rajatsen91** [comment]
Done. I did not get errors even initially just a lot of warnings. Now they are gone after this commit.
