### ISSUE TITLE
Possible error in the implementation compared to paper?

### ISSUE THREAD

**Issue by adam2392** [rajatsen91/CCIT#9]
Hi,

Cool paper and thanks for uploading the code. Really interesting concepts put forward.

I perused the code and noticed that there is possibly a mismatch between what the implementation and the proposed algorithm do?

Specifically, https://github.com/rajatsen91/CCIT/blob/0b9dce9cf110573d21eebaded1b088dbca10541c/CCIT/CCIT.py#L97-L103
builds a NearestNeighbor tree search using all of the "training data" or what is called (U = U_1 \cup U_2) in Algorithm 1 of the paper. Then it queries the nearest neighbor inside the entire U dataset again. 

Instead Algorithm 1 proposes that one should be construct the NearestNeighbor tree on a distinct set, U_2 dataset, and then query elements in U_1, swapping `y` with `y'` for close by `z'` and `z`. @rajatsen91 is this an issue?

**Comment by karthikeyansh** [comment]
In the paper, we could not analyze the version in the code - so we use U1
and U2 split. Our theory will not work when u do nearest neighbor on the
combined dataset.

But in practice - if u use more samples - nearest neighbor approximation is
better and performance is better.
That's why we used it.
